//! OxideSEO Native Plugin: Markdown Report Exporter
//!
//! Generates a Markdown summary report from crawl data.
//! This is an example native exporter plugin.
//!
//! Build: `cargo build --release`
//! Output: `target/release/libmarkdown_exporter.dylib` (macOS)
//!         `target/release/libmarkdown_exporter.so` (Linux)
//!         `target/release/markdown_exporter.dll` (Windows)

use serde::Deserialize;

/// Crawl data received as JSON from the host.
#[derive(Debug, Deserialize)]
struct CrawlExportData {
    crawl_id: String,
    start_url: String,
    urls_crawled: u64,
    urls_errored: u64,
    issues: Vec<ExportIssue>,
}

#[derive(Debug, Deserialize)]
struct ExportIssue {
    rule_id: String,
    severity: String,
    message: String,
    url: Option<String>,
}

/// Generate a Markdown report from crawl data.
pub fn generate_markdown(data_json: &str) -> Result<String, String> {
    let data: CrawlExportData =
        serde_json::from_str(data_json).map_err(|e| format!("JSON parse error: {e}"))?;

    let mut md = String::new();

    // Header
    md.push_str(&format!("# OxideSEO Crawl Report\n\n"));
    md.push_str(&format!("**Crawl ID:** {}\n\n", data.crawl_id));
    md.push_str(&format!("**Start URL:** {}\n\n", data.start_url));

    // Summary stats
    md.push_str("## Summary\n\n");
    md.push_str(&format!("| Metric | Value |\n"));
    md.push_str(&format!("|--------|-------|\n"));
    md.push_str(&format!("| URLs Crawled | {} |\n", data.urls_crawled));
    md.push_str(&format!("| URLs Errored | {} |\n", data.urls_errored));
    md.push_str(&format!("| Total Issues | {} |\n\n", data.issues.len()));

    // Issue counts by severity
    let errors = data.issues.iter().filter(|i| i.severity == "error").count();
    let warnings = data
        .issues
        .iter()
        .filter(|i| i.severity == "warning")
        .count();
    let infos = data.issues.iter().filter(|i| i.severity == "info").count();

    md.push_str("## Issues by Severity\n\n");
    md.push_str(&format!("- **Errors:** {errors}\n"));
    md.push_str(&format!("- **Warnings:** {warnings}\n"));
    md.push_str(&format!("- **Info:** {infos}\n\n"));

    // Top issues
    if !data.issues.is_empty() {
        md.push_str("## Top Issues\n\n");
        md.push_str("| Severity | Rule | Message | URL |\n");
        md.push_str("|----------|------|---------|-----|\n");

        for issue in data.issues.iter().take(50) {
            let url = issue.url.as_deref().unwrap_or("-");
            md.push_str(&format!(
                "| {} | {} | {} | {} |\n",
                issue.severity, issue.rule_id, issue.message, url
            ));
        }
    }

    md.push_str("\n---\n*Generated by OxideSEO*\n");

    Ok(md)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_markdown() {
        let data = r#"{
            "crawl_id": "test-123",
            "start_url": "https://example.com",
            "urls_crawled": 42,
            "urls_errored": 3,
            "issues": [
                {"rule_id": "meta.title_missing", "severity": "error", "message": "Page has no title tag", "url": "https://example.com/about"},
                {"rule_id": "meta.desc_missing", "severity": "warning", "message": "Page has no meta description", "url": null}
            ]
        }"#;

        let md = generate_markdown(data).unwrap();
        assert!(md.contains("# OxideSEO Crawl Report"));
        assert!(md.contains("test-123"));
        assert!(md.contains("URLs Crawled | 42"));
        assert!(md.contains("meta.title_missing"));
        assert!(md.contains("Errors:** 1"));
        assert!(md.contains("Warnings:** 1"));
    }

    #[test]
    fn test_invalid_json() {
        let result = generate_markdown("not json");
        assert!(result.is_err());
    }
}
